### ISSUE TITLE
Help flag not found and errors do not make sense

### ISSUE THREAD

**Issue by saracalihan** [axe-api/axe-magic#10]
I install the cli to create my first **_axe-api_** project and then ran the `--help` command but the cli gave me an illegible error. There is no help flag and it returns an error directly to the user when running commands that do not exist, it can look prettier :)

**output**:
![Screenshot_20210906_155718](https://user-images.githubusercontent.com/56413673/132221920-e54c99e8-c21e-4e3c-aa62-6f29592f9e7b.png)

`axe-api` command directly outputs usage information, but running the `--help` or `-h` command directly will be much easier for noob developers like me.

**Comment by ozziest** [comment]
Hi,

Thank you very much @saracalihan, it is a good catch! :rocket: I am going to review your PR immediately.

**Comment by ozziest** [comment]
It should be working correctly with the new version. Thank you very much for your time. :clap:
