### ISSUE TITLE
npm package is outdated

### ISSUE THREAD

**Issue by frknbasaran** [axe-api/axe-magic#4]
this is why "new" command not works as should be. it can't clone example repository from git.

https://github.com/adonisx/adonisx-cli/commit/1bc1650540bf058001a70e7893a18826a32e77cd#diff-33b2356599756995a4d3cf5f87910680

the commit above already fixed the reason of problem but it's not synced to npm registry.

**Comment by ozziest** [comment]
Thanks for the feedback. :heart: 

We are going to create an auto-deployment pipeline (#5). But for a quick fix to solve your problem, we published the correct version to the NPM. 

May you check it out, please?
